### ISSUE TITLE
Error received on Windows 10 x64. "Device is not open"

### ISSUE THREAD

**Issue by markosole** [pgsamila/HIDtoComPort#2]
Hi, I've tried this and compiled it without any problems (just had to install missing hid library). 
After running it and on Read Device I get error message Device is not open.

I would guess that windows does not give rights to this app to open HID device.
Any ideas?

**Comment by pgsamila** [comment]
I tested on Windows 10 x64. It works fine. You need virtual coupled serial ports. select 1 serial port from HID to Com port app and run the app. You can read the HID device data from the other serial port. -> you will get HEX bytes - seperated.
For virtual coupled serial ports, you can use [virtual comports software](https://www.virtual-serial-port.org/).
